/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BanksRouteImport } from './routes/banks'
import { Route as BillsRouteImport } from './routes/bills'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as ChecksRouteImport } from './routes/checks'
import { Route as CustomersRouteImport } from './routes/customers'
import { Route as ForecastRouteImport } from './routes/forecast'
import { Route as InvoicesRouteImport } from './routes/invoices'
import { Route as LedgerRouteImport } from './routes/ledger'
import { Route as ReceiptsRouteImport } from './routes/receipts'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as VendorsRouteImport } from './routes/vendors'
import { Route as PrintInvoiceIdRouteImport } from './routes/print.$invoiceId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BanksRoute = BanksRouteImport.update({
  id: '/banks',
  path: '/banks',
  getParentRoute: () => rootRouteImport,
} as any)
const BillsRoute = BillsRouteImport.update({
  id: '/bills',
  path: '/bills',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const ChecksRoute = ChecksRouteImport.update({
  id: '/checks',
  path: '/checks',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersRoute = CustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => rootRouteImport,
} as any)
const ForecastRoute = ForecastRouteImport.update({
  id: '/forecast',
  path: '/forecast',
  getParentRoute: () => rootRouteImport,
} as any)
const InvoicesRoute = InvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => rootRouteImport,
} as any)
const LedgerRoute = LedgerRouteImport.update({
  id: '/ledger',
  path: '/ledger',
  getParentRoute: () => rootRouteImport,
} as any)
const ReceiptsRoute = ReceiptsRouteImport.update({
  id: '/receipts',
  path: '/receipts',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const VendorsRoute = VendorsRouteImport.update({
  id: '/vendors',
  path: '/vendors',
  getParentRoute: () => rootRouteImport,
} as any)
const PrintInvoiceIdRoute = PrintInvoiceIdRouteImport.update({
  id: '/print/$invoiceId',
  path: '/print/$invoiceId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/banks': typeof BanksRoute
  '/bills': typeof BillsRoute
  '/calendar': typeof CalendarRoute
  '/checks': typeof ChecksRoute
  '/customers': typeof CustomersRoute
  '/forecast': typeof ForecastRoute
  '/invoices': typeof InvoicesRoute
  '/ledger': typeof LedgerRoute
  '/receipts': typeof ReceiptsRoute
  '/register': typeof RegisterRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/vendors': typeof VendorsRoute
  '/print/$invoiceId': typeof PrintInvoiceIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/banks': typeof BanksRoute
  '/bills': typeof BillsRoute
  '/calendar': typeof CalendarRoute
  '/checks': typeof ChecksRoute
  '/customers': typeof CustomersRoute
  '/forecast': typeof ForecastRoute
  '/invoices': typeof InvoicesRoute
  '/ledger': typeof LedgerRoute
  '/receipts': typeof ReceiptsRoute
  '/register': typeof RegisterRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/vendors': typeof VendorsRoute
  '/print/$invoiceId': typeof PrintInvoiceIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/banks': typeof BanksRoute
  '/bills': typeof BillsRoute
  '/calendar': typeof CalendarRoute
  '/checks': typeof ChecksRoute
  '/customers': typeof CustomersRoute
  '/forecast': typeof ForecastRoute
  '/invoices': typeof InvoicesRoute
  '/ledger': typeof LedgerRoute
  '/receipts': typeof ReceiptsRoute
  '/register': typeof RegisterRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/vendors': typeof VendorsRoute
  '/print/$invoiceId': typeof PrintInvoiceIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/banks'
    | '/bills'
    | '/calendar'
    | '/checks'
    | '/customers'
    | '/forecast'
    | '/invoices'
    | '/ledger'
    | '/receipts'
    | '/register'
    | '/reports'
    | '/settings'
    | '/vendors'
    | '/print/$invoiceId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/banks'
    | '/bills'
    | '/calendar'
    | '/checks'
    | '/customers'
    | '/forecast'
    | '/invoices'
    | '/ledger'
    | '/receipts'
    | '/register'
    | '/reports'
    | '/settings'
    | '/vendors'
    | '/print/$invoiceId'
  id:
    | '__root__'
    | '/'
    | '/banks'
    | '/bills'
    | '/calendar'
    | '/checks'
    | '/customers'
    | '/forecast'
    | '/invoices'
    | '/ledger'
    | '/receipts'
    | '/register'
    | '/reports'
    | '/settings'
    | '/vendors'
    | '/print/$invoiceId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BanksRoute: typeof BanksRoute
  BillsRoute: typeof BillsRoute
  CalendarRoute: typeof CalendarRoute
  ChecksRoute: typeof ChecksRoute
  CustomersRoute: typeof CustomersRoute
  ForecastRoute: typeof ForecastRoute
  InvoicesRoute: typeof InvoicesRoute
  LedgerRoute: typeof LedgerRoute
  ReceiptsRoute: typeof ReceiptsRoute
  RegisterRoute: typeof RegisterRoute
  ReportsRoute: typeof ReportsRoute
  SettingsRoute: typeof SettingsRoute
  VendorsRoute: typeof VendorsRoute
  PrintInvoiceIdRoute: typeof PrintInvoiceIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/banks': {
      id: '/banks'
      path: '/banks'
      fullPath: '/banks'
      preLoaderRoute: typeof BanksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bills': {
      id: '/bills'
      path: '/bills'
      fullPath: '/bills'
      preLoaderRoute: typeof BillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checks': {
      id: '/checks'
      path: '/checks'
      fullPath: '/checks'
      preLoaderRoute: typeof ChecksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers': {
      id: '/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof CustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forecast': {
      id: '/forecast'
      path: '/forecast'
      fullPath: '/forecast'
      preLoaderRoute: typeof ForecastRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invoices': {
      id: '/invoices'
      path: '/invoices'
      fullPath: '/invoices'
      preLoaderRoute: typeof InvoicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ledger': {
      id: '/ledger'
      path: '/ledger'
      fullPath: '/ledger'
      preLoaderRoute: typeof LedgerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/receipts': {
      id: '/receipts'
      path: '/receipts'
      fullPath: '/receipts'
      preLoaderRoute: typeof ReceiptsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendors': {
      id: '/vendors'
      path: '/vendors'
      fullPath: '/vendors'
      preLoaderRoute: typeof VendorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/print/$invoiceId': {
      id: '/print/$invoiceId'
      path: '/print/$invoiceId'
      fullPath: '/print/$invoiceId'
      preLoaderRoute: typeof PrintInvoiceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BanksRoute: BanksRoute,
  BillsRoute: BillsRoute,
  CalendarRoute: CalendarRoute,
  ChecksRoute: ChecksRoute,
  CustomersRoute: CustomersRoute,
  ForecastRoute: ForecastRoute,
  InvoicesRoute: InvoicesRoute,
  LedgerRoute: LedgerRoute,
  ReceiptsRoute: ReceiptsRoute,
  RegisterRoute: RegisterRoute,
  ReportsRoute: ReportsRoute,
  SettingsRoute: SettingsRoute,
  VendorsRoute: VendorsRoute,
  PrintInvoiceIdRoute: PrintInvoiceIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
